language: cpp

sudo: false

compiler:
  - gcc
#  - clang

env:
  global:
    # Coverity Scan token
    secure: "JdTWcMl0EQHSuaT9LYFyixjVhV9270V8cLgJDBxeQ3j2s9uJ6BMAdFVNDeo1PS33YjgqbPTXbmyCklPld11H5UYtWDg5MvjYyIKro1zjy46Q3klaYGUUcmSVhvqEqtJldmngoQEVHw78sOXHnpuROt8hdtYzO38Wqgrfy3DdtVQ="

addons:
  apt:
    #ref: https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - george-edison55-precise-backports # cmake 3.2.3
    #ref: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    packages:
      - gcc-5
      - g++-5
      - clang-3.7
      - cmake
      - cmake-data
  coverity_scan:
    project:
      name: polserver/polserver
    build_command_prepend: export CXX="g++-5" CC="gcc-5";cmake ../..
    build_command: make -j2
    branch_pattern: coverity
    notification_email: turley@polserver.com
   
before_install:
  - cd lib
  - tar xjf boost_1_55_0.tar.bz2
  - cd ../pol-core/bin-build
  - chmod a+x build_linux.sh

script:
  - export TRAVIS_CI=1
  - if [ "$CXX" = "g++" ]; then 
      export CXX="g++-5" CC="gcc-5";
    fi
  - if [ "$CXX" = "clang++" ]; then 
      export CXX="clang++-3.7" CC="clang-3.7";
    fi
  - ./build_linux.sh

  - cd ../../testsuite/escript
  - /usr/bin/python performtests.py -c ../../pol-core/bin/ecompile -r ../../pol-core/bin/runecl

